### ISSUE TITLE
Environment Variables for Deployment

### ISSUE THREAD

**Issue by Flinty916** [flozero/nuxt-stripe#38]
Hi!

I'm curious how I can deploy my app using this package with keys set as environment variables?

I don't see anything in documentation regarding this, and would be very appreciative if you can point me in the right direction. 

My environment is Kubernetes based, so this is rather important that I can get the keys from a runtime environment variable. 

Thanks!

**Comment by flozero** [comment]
hey @Flinty916  hope you are doing good .

I believe you should be able to achieve that by using your env variables 

https://github.com/fuentesloic/nuxt-stripe?tab=readme-ov-file#configuration

setup the key using the imports.meta or process.env depending on what do you use

Tell me how it goes

**Comment by flozero** [comment]
I am close this issue as I believe it is answerd with the new documentation :) If not please re open it @Flinty916
